# Genetics and Genomics {#g2}

## Introduction
A haplotype block is a set of closely linked alleles or markers on a chromosome that tend to be inherited together over evolutionary time.

Across Eukaryotes, the frequency of recombination is inversely proportional to overall genome size. The result is that yeast have a recombination rate a few orders of magnitude higher than that of humans (She and Jarosz, 2018).

```{r, include=FALSE}
options(tinytex.verbose = TRUE)
```

### Subpoint
This is some sub info

### Second subpoint
A haplotype block is a set of closely linked alleles or markers on a chromosome that tend to be inherited together over evolutionary time.

Across Eukaryotes, the frequency of recombination is inversely proportional to overall genome size. The result is that yeast have a recombination rate a few orders of magnitude higher than that of humans (She and Jarosz, 2018).

## DNA Replication
When the origin of replication(s) is removed from bacteria or eukaryotes, growth and division is restricted or entirely eliminated, but in some strains of archaea like H volcanii, deletion of the origin of replication accelerates cell growth rates. It turns out that this archaea can use a process that is similar to homologous recombination to create a replication fork and replicate its chromosome (Hawkins et al., 2013).

## Mutation Rate
### Observed Mutation Rates
Using whole-genome sequencing or next-gen sequencing to determine mutation rates by base, it appears that C>T mutations at CpG sites mutate at a frequency of 10-7 changes/cell division, and all other sites are within the range of 10^-8 - 10^-9 base changes per division (Arnheim and Calabrese, 2009, 2016; Campbell and Eichler, 2013; Ségurel et al., 2014; @kong2012rate; @segurel2014determinants).

It appears that humans have the highest germline mutation rate of all analyzed species (Lynch, 2016). It also appears from trio sequencing that both human and chimp mutation rates are in the range of 1.0-1.25x10^-8 mutations per site per generation [@kong2012rate].

While germline mutation rates are similar in chimps and humans, there are important differences, one example being that CpG mutations are more prevalent in the chimp germline [@venn2014strong].

Possibly supporting the somatic theory of aging, increases and reductions in DNA damage rates may accelerate and decelerate, respectively, some aspects of aging [@behjati2014genome; @altieri2008dna].

### Mutation Rate Evolution
Providing an example of how human mutation rates can differ by geographic origination, Europeans compared to African/Asian populations have a 1.6 increased mutation rate of a TCC->TTC transitions (Harris, 2015). This change in DNA replication fidelity appears to have happened 40-80kya when Europeans and Asians diverged and illustrates that DNA repair rates have not remained entirely stable throughout human evolution.

Just as in humans show a number of different mutational likelihoods, the great apes apes also show evolution in the rates of different triplet-context mutation rates [@harris2017rapid]. It would be interesting to investigate how these different rates have constrained evolution, if at all.

Killifish seem to exhibit an elevation in mutation rates, and exhibit chromosomal expansions and deleterious mutations especially in mitochondrial genes and nuclear genes important for late life. It seems that killifish show evidence of their lifespan being limited by many deleterious mutations of small effect-size in a manner that is compatible with neutral theory of evolution [@ohta1973model; @kimura1968evolutionary]. The overall idea is that when adapting to annual niches, killifish experienced intense selection on genes affecting traits important for early life, and a corresponding relaxation of selection on traits affecting later life in a manner compatible with neutral theory [@cui2019relaxed]. It is important to note that the authors do not test for antagonistic pleiotropy, so this effect may be playing an important role in the development of detrimental aging-related mutations [@charlesworth2000degeneration; @williams1957pleiotropy].

## Mutation Hotspots
There are a number of sporadic mutation hotspots associated with disease incidence, like achondroplasia which has a sporadic incidence rate of 4.5 x 10-5 per generation (Arnheim and Calabrese, 2016; Waller et al., 2008). This disease originates from a single mutation in the FGFR3 gene at a mutation rate ~450 times higher than what would ordinarily be expected at a CpG site (Bellus et al., 1995; Rousseau et al., 1994; Shiang et al., 1994).

## Mutation Detection
Pyrophosphorolysis-activated polymerization is a mutation detection method that can detect a single mutant molecule of DNA within 25,000 genomes (Liu and Sommer, 2004; Qin et al., 2007).

Detecting cancer from cfDNA is often done by mutation detection alone, however, fragment size of the cfDNA seems to be non-randomly linked to malignant state. Using the ratio of short to long cfDNA fragments calculated for 5MB windows, combined with mutation detection within collected cfDNA seems to quite accurately predict cancerous state for a number of different solid cancers [@cristiano2019genome]. It appears that in individuals without cancer, the majority of cfDNA originates from
leukocytes, and is fragmented in a manner that is dependent on nucleosomal patterns. As solid tissue burden grows and the associated cells release cfDNA, that DNA fragments according to the solid tissue nucleosomal patterns, and this seems to be sufficiently distinct from the fragmentation patterns of leukocyte DNA.

## Genetic Modifications
Caffeine was cloned to allow for caffeine-deficient coffee and teas without the decaffeination process (Kato et al., 2000).

When a DNA-associating protein from tardigrades was cloned into mammalian cells, they became about 40% more tolerant to radiation (Hashimoto et al., 2016).

## Sequencing Methods
Using a new sequencing method called sci-RNA-seq, the transcriptome of every cell of 762 cells in C Elegans was sequenced to yield single-cell sequencing results and transcriptome profiling of every cell in the body. The way this is done is by methanol fixing nuclei and then incorporating a UMI when converting to cDNA, then mixing cells again and incorporating another UMI when synthesizing the other strand (Cao et al., 2017).

It appears that DAPI does not increase sequencing error rates by Illumina sequencing (Leung et al., 2016).

One group came up with a method that is essentially identical to mine in which they use barcoded probes to detect leukemia but they tracked the mutation manually and ignored background (Wong et al. 2015)

### Lineage Tracing
Because mutation rates in mitochondrial DNA are higher than for genomic DNA, and they are heterogeneous, single cell ATAC-Seq of the mitochondrial can be effectively used alone or in combination with RNASeq for lineage tracing [@ludwig2019lineage]. This is an especially advantageous approach, as it requires no alterations to the organism of interest, allowing its application in humans.

## Diagnostics
In Li and Snyder Cell 2018, the EHR from hospitals is used to integrate with a machine learning algorithm trained on aneurysm detection. Patients are then whole genome sequenced, and the genome sequencing plus the lifestyle of the individual on EHR is then used to predict if the person has an aneurysm. They were able to achieve pretty robust detection results that could then be used in a prediction setting in the clinic.

## Detecting Common Diseases
Much of the following information comes from this review: [@shendure2019genomic].

Linkage disequilibrium studies were designed to detect Mendelian diseases
GWAS designed back in 1996 to detect non-mendelian multigenic traits that have much less penetrant effects
The promise that GWAS could risk stratify people for diseases has been challenging because most diseases seem to be driven by an extremely large number of variants with small effects that will likely require extremely large sample sizes
There exists a problem of missing heritability, and it was often believed that common SNPs only held part of the puzzle, and more rare variants accounted for a great deal of heritability, but this does not yet seem to be the case, and SNPs seem to have a much greater effect size
Another problem with GWAS is it is haplotype specific in that it can implicate a stretch of DNA inherited from one parent, but is blind to the individual effect sizes of each of the individual variants
A challenge raised by Jonathan Pritchard is that gene regulatory networks are so interconnected that variants in one gene may actually cause changes in other genes and are therefore only peripherally relevant to a phenotype
One continued promise of the utility of GWAS to identify the causal genetics behind diseases is that most of the strongest GWAS associations came from small studies of european populations that identified mutations of large effect sizes. By expanding studies to populations, especially those like african populations that have less linkage disequilibrium many more variants of large effect sizes could be identified and used to tease out relationships of smaller effect sizes in other populations.
Methods are also improving fo linking regulatory elements to the genes they regulate like (Gasperini et al. 2018; Gasperini et al. 2019).
Linking regulatory elements to their corresponding genes can be quite helpful, because this information can be incorporated into GWAS calculations to refine causal linkage probabilities.
Polygenic risk scores have often been used to predict phenotypic variance in plants and animals, and have yet to really be applied to human genomics (Khera et al. 2018).
Training of PRSs seem to not require fine-mapping, and their use has been aided by the UK Biobank (Bycroft et al. 2018).

## Detecting Rare Diseases
There are some 7k Mendelian monogenic disorders that impact about 0.5% of live births, but contribute to about 70% of pediatric hospital admissions
An important surprise has been that de-novo mutations account for a substantial amount of intellectual disabilities and autism, where as many as 30-60% of ASD is caused by de-novo mutations
Currently as many as half of acutely ill inpatient infants can be diagnosed from WGS.
There are currently 59 genes designated by the American College of Medical Genetics as being sufficiently clinically actionable as to warrant sequencing and reporting in patients (Kalia et al. 2017).

## Tissue Evolution
By sequencing 7,664 tumors spanning 29 different cancer types, it appears that unlike species evolution, the force of positive selection in developing tumors outweighs that of negative selection as evidenced by the loss of less than 1 coding nucleotide substitution per tumor [@martincorena2017universal]. The number of mutations per cancer varied from 1 per thyroid and testicle cancer to over 10 per endometrial and colorectal cancers. This information helps to answer how many mutations are needed to effectively create cancers and how this can vary with across tissue types. A number of groups have tried to answer these questions in the past by mathematically estimating the number of rate limiting steps required in the process of oncogenesis [@armitage1954age; @tomasetti2015variation]. There are two important problems with this approach, first that not all driver mutations need to be rate-limiting [@yates2015subclonal], and not all rate limiting steps in oncogenesis need to be driver mutations [@martincorena2015high]. It has also been problematic to sequence tumors and count the number of high frequency mutations in oncogenic genes, but this has the added challenges of distinguishing passenger from driver mutations and is limited to current lists of oncogenes. Lists of genes involved in cancer have become increasingly detailed, but are still limited [@lawrence2014discovery; @kandoth2013mutational]. The absence of negative selection in cancer may well indicate how dispensable the majority of genes are for somatic cells.

In their paper, Martincorena and Campbell show that the dN/dS ratio for somatic tissues and cancer tissue is 1 or greater showing that the effect of negative selection is minimal. In contrast, the dN/dS for germline species evolution is less than 0.5 showing a much greater effect of negative selection. Surprisingly, the non-synonymous mutations showed a dN/dS ration of 1 whether they existed in haploid or diploid regions suggesting the cells were not simply tolerating the mutations by having two copies.

Using sequencing of blood to find spontaneous mutations and go back and use population biology to calculate the number of HSCs, it was found that there were between 50k-200k HSCs contributing to hematopoiesis at any given time [@lee2018population].

Using a method they developed called RNA-MuTect, mutations from RNA are found and matched with germline DNA. Using samples within TCGA that had DNA and RNA extractions from the same individual from multiple tissues, RNA-MuTect identifies multiple putatively oncogenic mutations from across otherwise normal tissues [@Yizhak2019-ch]. The numbers of detected oncogenic mutations was dependent upon tissue exposure to mutagens, proliferation rate, and tissue architecture.

## Mutational Processes in Cancer
Most cancers carry between 1,000 and 20,000 somatic point mutations and a few hundred insertions, deletions, and rearrangements [@martincorena2015somatic]. Leukemias and pediatric brain cancers typically contain the lowest numbers of mutations while those tissues exposed to mutagens like lung and skin cancers tend to have the highest numbers [@stephens2009complex; @alexandrov2013signatures; @lawrence2013mutational; @vogelstein2013cancer]. It is interesting to note that from the Cancer Gene Census database, it appears that only three genes; TP53, PIK3CA, and BRAF are mutated in 10% or more patients [@martincorena2015somatic].

Carcinogens or particular mutations often cause identifiable mutational patterns. BRCA1 and BRCA2 mutations commonly associated with breast, ovarian, and pancreatic cancers are associated with particular substitution patterns, small indels, and large chromosome duplications [@nik2012mutational].

While mutations in TP53 and NOTCH1 can cause an imbalance in the division symmetry of stem cells in intestinal crypts by increasing the ratio of proliferation to differentiation[@klein2010stochastic; @alcolea2014differentiation], mutations like APC and KRAS can increase the rates of crypt fission to allow multiple crypts to become clonal [@preston2003bottom; @snippert2014biased].

## Mutagenesis in Cancer
### Mutation Rates
Substitution rates in B/T lymphocytes appears to be on the order of 2 to 10 mutations per diploid genome per cell division, a rate which may be about 10 times higher than that occurring in germ cells [@lynch2010rate].

### Mutation Load
Sun exposed skin cells can carry thousands of point mutations, and about 25-30% of these cells have acquired at least one driver mutation, and yet, while positive selection is evident as the clones expand, clone sizes are relatively similar across individuals suggesting that some mechanism is constraining the expansion of driver clones [@martincorena2015somatic].

The progression of Barrett's esophagus to esophageal adenocarcinoma shows no significant increase in mutation load. This may mean that Barrett's esophagus is an advanced precancerous lesion, but some other step in the tissue is required for it to transition into such a stage [@gusev2014partitioning].

## Genetic Manipulation
### Cloning
A macaque was the first primate to be cloned by SCNT (Liu et al., 2018).

### Gene Therapy
X-linked severe combined immunodeficiency (SCID-X1) (commonly referred to as bubble-boy disease) is caused by mutations within the IL2RG gene which impairs the receptor for IL-2, IL-4, IL-7, IL-9, IL-15 and IL-21. The result of these mutations is that T and NK cells fail to develop. This disease is often treated with bone marrow transplant which involves irradiation. Instead of such a treatment, low-dose busulfan has been used in combination with WT IL2TG DNA carrying lentivirus to give HSCs a functional copy of the receptor. This treatment seems to allow T and NK cells to develop with minimal harm to the patient [@Mamcarz2019-ei].

The use of CRISPR technology to edit RNA may have significant therapeutic potential gene expression could be transiently controlled. One concern of RNA editing is that the CRISPR system would likely have to be activated in a human the entire time an effect is desired. This long-term CRISPR activation would likely cause an immune response against the bacterial Cas protein. Rauch et al developed a largely humanized Cas protein using human proteins which may significantly reduce the immunogenic potential [@rauch2019programmable].

### Genetic Rescue
Inbreeding of a population can result in an accumulation of deleterious mutations. The accompanying loss in fitness can be mitigated through outbreeding, as it can increase heterozygosity and thereby mask recessive deleterious alleles [@keller2002inbreeding; @ingvarsson2001restoration; @vila2003rescue]. This effect depends on the principle of overdominance or heterozygous vigour, which is a condition where a heterozygous offspring has a higher fitness than either of the parents.

Using a modeling approach, it appears that genetic rescue of a species will result in a substantial loss of the original genes of an organism. According to the models, the degree of genetic replacement of additive genes will proportionally match the genetic rescue, while the replacement of recessive genes may not need to occur as much as they will be masked by the foreign alleles [@Harris2019-sm]. One caveat to this, is that even if a large fraction of the genome in the inbred organism is recessive, it is likely that a substantial portion of it must be lost to restore fitness, as it is more likely that most of the recessive mutations contribute to the reduction in fitness, each with a small fitness effect, rather than only a handful of the mutations contributing with a large fitness effect.

### Mitochondria
While the mechanism appears to still be unclear [@chen2013mechanism], mtDNA can undergo recombination, direct evidence of which was first found in an individual that was heterologous for paternal and maternal inheritance of mitochondria [@kraytsberg2004recombination].

### Evolution
In the codfish, it appears that the one of the genes they use to allow them to freeze without damaging cells did not evolve from the duplication of a different gene that was then altered to produce its current function, but rather, it appears to have evolved from a non-functional portion of the genome [@baalsrud2017novo]. This constitutes some of the first evidence that genes can result from the de-novo use of junk DNA to create an entirely novel gene, rather than repurposing
another gene.
