# Neuroscience {#neurosci}

## Alzheimer's Disease 
It seems that the bacteria Porphyromonas gingivalis may be partially responsible for exacerbating symptoms in people with AD. Observation of the bacteria in the brains of people with AD showed evidence that the bacteria secreted proteases called gingipains that increased Aβ production and were also neurotoxic. Inhibition of the proteases reduced neuroinflammation and rescued neurons in the hippocampus [@dominy2019porphyromonas].

Tied both to sleep and AD, it appears that chronic sleep deprivation increases the formation of Aβ plaques, perhaps suggesting that sleep is protective against the formation of the plaques that eventually lead to AD [@Holth2019-cd]. 

## Parkinson's Disease
Early onset PD is associated with mutations in PINK1 kinase and PRKN ubiquitin ligase. Inactivating mutations within these genes cause nearly 100% penetrance of PD in humans, but had not previously shown the same penetrance in mice. It turns out that exposure to gram-negative bacteria causes antigen presentation of mitochondrial proteins in the mutant mice, resulting in the brain infiltration of CD8 cells which target these mitochondrial antigens. These CD8 T cells in the brain kill dopaminergic neurons and result in PD symptoms. It therefore appears that PD incidence is the result of infection [@matheoud2019intestinal].

## Sleep
Sleep deprivation results in the global phosphorylation of the brain proteome, an effect which is reversed by sleep. A mouse mutant for SIK3 causes mice to sleep more, and may play an important role in the cause of sleep desire [@wang2018quantitative].
